version: "3.9"

networks:
  public:
    # This network is exposed
    driver: bridge
    name: public
  internal:
    # This Docker network is only used for the database.
    driver: bridge
    name: internal
    internal: true

services:
  database:
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - database:/bitnami/mariadb
      - database_seed:/docker-entrypoint-initdb.d
    env_file: env/db.env
    networks:
      - internal
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mariadb/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6
    restart: always
  
  api:
    build: api
    ports:
      - '3000:3000'
    depends_on:
      database:
        condition: service_healthy
    env_file: ../UA-api/.env
    networks:
      - public
      - internal
    restart: always
  front:
    build: front
    ports:
      - 8080:8080
    env_file: ../UA-front/.env
    networks:
      - public