version: "3.9"

networks:
  public:
    # This network is exposed
    driver: bridge
    name: public
  internal:
    # This Docker network is only used for the database.
    driver: bridge
    name: internal
    internal: true

services:
  database:
    image: #to complete
    volumes:
      - database: #to complete
    env_file: ../UA-api/.env
    networks:
      - internal
    healthcheck: #???
      test: ["CMD", "/opt/bitnami/scripts/mariadb/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6
    restart: always
  
  api:
    build: api
    ports:
      - '3000:3000'
    depends_on:
      database:
        condition: service_healthy
    env_file: ../UA-api/.env
    networks:
      - public
      - internal
    restart: always
  front:
    build: front
    ports:
      - 8080:8080
    env_file: ../UA-front/.env
    networks:
      - public

  adminer:
    image: #to complete
    restart: always
    ports:
      - #to complete
    networks:
      - public
      - internal
  grafana:
    image: #to complete
    ports:
      - 
    volumes:
      - grafana: #to complete
    networks:
      - public
      - internal
    restart: always
  
  filemanager:
    image: #to complete
    volumes:
    env_file:
    ports:


  volumes:
  database:
    driver: local
    name: ua_db
  database_seed:
    driver: local
    name: ua_seed
  grafana:
    driver: local
    name: ua_grafana